language: python
cache: pip
python:
- 3.5
- 3.7

services:
  - redis-server

before_install:
- pip install codecov

install:
- pip install -r requirements.txt

script:
- coverage run --rcfile=.coveragerc tests.py

after_success:
- coverage report
- codecov

branches:
  only:
  - master